services:
  nodejs-app:
    build:
      context: ./api
      args:
        NODE_ENV: test
    image: auth-api-test:latest
    environment:
      NODE_ENV: test
    container_name: auth-api
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env.test
    command:
      ['npm','test']
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: auth-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
