services:
  nodejs-app:
    build:
      context: ./api
      args:
        NODE_ENV: production
    image: auth-api:latest
    container_name: auth-api
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    command:
      ['npm','start']
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: auth-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
