name: command Workflow
on: ['push']

jobs:
  command:
    runs-on: ubuntu-latest
    steps:
      - name: depuge group
        run: |
          echo "::group:: my group msg "
          echo "my msg 1"
          echo "my msg 2"
          echo "::endgroup::"
      - name: env variable
        run: |
          echo "my-name=ahmed" >> $GITHUB_ENV
      - name: print the variable
        run: |
          echo $my-name